index_number:
    path: /number
    controller: App\Controller\DijitiController::number

index_text:
    path: /text
    controller: App\Controller\DijitiController::text

inserisci_utente:
  path: /number/inserisci
  controller: App\templates\InserisciController.php::insert
