index_index:
    path: /index
    controller: App\Controller\DijitiController::index

index_insert:
    path: /index/inserito
    controller: App\Controller\DijitiController::insert

index_delete:
    path: /index/eliminato
    controller: App\Controller\DijitiController::delete
